### ISSUE TITLE
Overwriting of air quality status

### ISSUE THREAD

**Issue by Onyxmoon** [Defensor7/homebridge-airmonitor#2]
I would like to use this issue to thank you for the creation.

But nevertheless I found a bug:
In my opinion the code has the error that the displayed air quality status is always determined by the CO2 value. The other values are calculated correctly but the current code does not take into account that one status could be more worse than the previous one. 

Suggestion for improvement:

Either the values have to be put into relation and calculated from the mix of air quality statuses or only the worst status is displayed.
Both solutions are not unreasonable.  Probably even the worst status would be the best to display, since air quality does not improve from a health point of view just because the other values compensate bad ones.

I believe the color coding on the device itself uses the same process. Even if the other values are good, the display turns orange to red when one value is bad (at the overview page of all values).

**Comment by andrewtzn** [comment]
I think having an option to customize the values for air quality levels of each sensor (PM2.5,VOC,CO2) would be a solution to Onyxmoon's issue.

By adding options to customize to values for Excellent, Good, Fair, etc..., would also add support for changing AQI standards for different countries.

**Comment by Onyxmoon** [comment]
That would be wonderful too. Nevertheless, all values should of course be taken into account to determine the air quality.

**Comment by Defensor7** [comment]
Thank your for report.
Error fixed in v.0.0.3, please update plugin.
Now plugin correctly returns the worst status.

**Comment by Defensor7** [comment]
> By adding options to customize to values for Excellent, Good, Fair, etc..., would also add support for changing AQI standards for different countries.

Customizing will be available in few weeks.
