### ISSUE TITLE
Add an option to disable CO2 sensor

### ISSUE THREAD

**Issue by andrewtzn** [Defensor7/homebridge-airmonitor#3]
Hi,

First of all, thank you for creating this plugin! :)
The CO2 is disabled on my monitor.
I am seeing a value of 99999ppm for CO2.

Please add an option to exclude CO2 from the air quality sensor.

Thank you again!
<img src="https://user-images.githubusercontent.com/9326712/81593080-eaaafb80-938c-11ea-85d4-f2e320673e2f.jpeg" width="350">

**Comment by Defensor7** [comment]
Options added, please update plugin and see README for examples.
